version: "3.9"
services:
  rag:
    build: .
    container_name: rag_bn_en
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./data:/app/data
      - ./.faiss_store:/app/.faiss_store
    restart: unless-stopped
