name: CI - RAG (FAISS + Gemini)

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      LLM_PROVIDER: gemini
      VECTOR_DB: faiss
      FAISS_DIR: .faiss_store
      EMBEDDING_MODEL: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
      TOP_K: 10
      CHUNK_SIZE: 800
      CHUNK_OVERLAP: 120
      # Gemini key injected from repo/org secrets
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env (for local code paths expecting it)
        run: |
          cat <<EOF > .env
          LLM_PROVIDER=gemini
          GOOGLE_API_KEY=${GOOGLE_API_KEY}
          VECTOR_DB=faiss
          FAISS_DIR=.faiss_store
          EMBEDDING_MODEL=sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
          TOP_K=10
          CHUNK_SIZE=800
          CHUNK_OVERLAP=120
          EOF

      - name: Create dummy PDF for CI
        run: |
          python .github/scripts/make_dummy_pdf.py

      - name: Ingest PDF -> FAISS
        run: |
          python -m src.ingest --pdfs data/*.pdf

      - name: Smoke test RAG (Python)
        run: |
          python -m src.ci_smoketest

      # --- OPTIONAL: Start API + curl it ---
      # - name: Run API + curl
      #   run: |
      #     uvicorn src.api:app --host 0.0.0.0 --port 8000 &
      #     sleep 5
      #     curl -X POST http://127.0.0.1:8000/ask \
      #      -H "Content-Type: application/json" \
      #      -d '{"question":"অনুপমের ভাষায় সুপুরুষ কাকে বলা হয়েছে?"}'
